# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: build movie info service

on:
  push:
    branches:
    - main
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - run: exit 1
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
   
    - name: Build with Maven
      run:  cd movie-info-servi && mvn clean package
    - name: copy artifact to staging
      run: mkdir staging && cp movie-info-service/target/*.jar staging
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: movie-info-service
        path: staging
